name: Cyber Snake - Fast Crawl

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Cyber Snake Animation
        uses: awesome-actions/github-contribution-snake-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file_name: output/github-contribution-grid-snake.svg
          color: "00ff00"        
          theme: "dark"          
          speed: "fast"          
